version: "3.9"

services:
  mqtt-broker:
    image: pet-mqtt-broker:latest
    container_name: mqtt-broker
    ports:
      - "8081:8081"
      - "1883:1883"
    networks:
      - pet-network

  pet-app:
    image: my-pet-project:latest
    container_name: pet-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mqtt-broker
    networks:
      - pet-network

networks:
  pet-network:
    driver: bridge
