version: "3.9"

services:
  mqtt-broker:
    image: pet-mqtt-broker:latest
    container_name: mqtt-broker
    ports:
      - "8081:8081"
      - "1883:1883"
    environment:
      - TZ=Europe/Moscow
    networks:
      - pet-network

  pet-app:
    image: pet-telegram-bot:latest
    container_name: telegram-bot
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: Europe/Moscow
    depends_on:
      - mqtt-broker
    networks:
      - pet-network

networks:
  pet-network:
    driver: bridge
